- name: Trigger Render Deploy
  run: |
    curl -X POST https://api.render.com/v1/services/srv-abc1234567890/deploys \
      -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
      -H "Content-Type: application/json" \
      -d '{}'
