name: Run SnarkyNews Daily

on:
  schedule:
    - cron: '0 1 * * *'  # runs every day at 1am UTC
  workflow_dispatch:     # optional: lets you trigger it manually in the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Call your Render endpoint
        run: |
          curl -X POST https://api.render.com/v1/services/srv-abc1234567890/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'

    
